services:
  - type: web
    name: flask-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn main:app
